- name: Demo on loops
  hosts: localhost
  tasks:
    - name: loops
      ansible.builtin.debug:
        msg: Fruit_name - {{ item }}
      loop:
        - apple
        - banana
        - orange


- name: Demo on loops
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - orange
  tasks:
    - name: loops
      ansible.builtin.debug:
        msg: Fruit_name - {{ item }}
      loop: "{{fruits}}"


- name: Demo on loops
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - orange
  tasks:
    - name: loops
      ansible.builtin.debug:
        msg: Fruit_name - {{ item }}
      loop:
        - { name: "apple", quantity: "100" }
        - { name: "banana", quantity: "200" }
        - { name: "orange", quantity: "300" }
